const getSupabase                 = require('../config/supabase');
const { generateQuestions }       = require('./questionBankGenerator');
const { buildPack, buildDynamicPack } = require('./packBuilder');

// ── Watermark thresholds ──────────────────────────────────────────────────────
// Per (module × difficulty) slot — minimum unassigned questions to maintain.
// Derived from: pack_questions / min_topics (2) = questions needed per slot.
const QUESTION_MIN = { easy: 6, medium: 9, hard: 12 };

// Minimum active packs to maintain per scope+branch.
const PACK_MIN = 3;

// Default questions per module for dynamic packs.
const DYNAMIC_QPM = 4;

// ── AutoGenerateQuestions ─────────────────────────────────────────────────────
// Fills a (module × difficulty) slot in question_bank if below its minimum.
async function autoGenerateQuestions({ curriculum, level, period, subject, module_number, difficulty }) {
  const supabase = getSupabase();

  const min = QUESTION_MIN[difficulty] || 6;

  let q = supabase
    .from('question_bank')
    .select('id', { count: 'exact', head: true })
    .eq('curriculum', curriculum)
    .eq('level', level)
    .eq('subject', subject)
    .eq('difficulty', difficulty)
    .eq('module_number', module_number)
    .eq('status', 'active')
    .is('assigned_pack_id', null);

  if (period) q = q.eq('period', period);
  else        q = q.is('period', null);

  const { count } = await q;
  const unassigned = count || 0;

  if (unassigned >= min) return; // already stocked

  const needed = (min - unassigned) + min; // generate double the gap as buffer
  console.log(`[autoGenerate] Slot ${level}/${period||'cap'}/${subject}/mod${module_number}/${difficulty} has ${unassigned} — generating ${needed}`);

  await generateQuestions({ curriculum, level, period: period || null, subject, module_number, difficulty, count: needed });
}

// ── AutoGeneratePack ──────────────────────────────────────────────────────────
// Ensures minimum pack count for a given scope + difficulty branch.
// Runs question generation first if any slot is low, then builds the pack.
async function autoGeneratePack({ curriculum, level, period, subject, difficulty }) {
  const supabase = getSupabase();
  const branch   = difficulty;

  // Check how many active packs already exist for this scope+branch
  let packQ = supabase
    .from('trial_packs')
    .select('id', { count: 'exact', head: true })
    .eq('curriculum', curriculum)
    .eq('level', level)
    .eq('subject', subject)
    .eq('branch', branch)
    .eq('status', 'active');

  if (period) packQ = packQ.eq('period', period);
  else        packQ = packQ.is('period', null);

  const { count: packCount } = await packQ;
  if ((packCount || 0) >= PACK_MIN) return; // already have enough

  // Ensure all slots are stocked before building
  const modules = await getActiveModules({ curriculum, level, period, subject });
  for (const { module_number } of modules) {
    for (const diff of ['easy', 'medium', 'hard']) {
      await autoGenerateQuestions({ curriculum, level, period, subject, module_number, difficulty: diff });
    }
  }

  // Build one pack (caller can invoke multiple times if needed)
  try {
    const result = await buildPack({ curriculum, level, period, subject, pack_type: 'general', difficulty });
    console.log(`[autoGenerate] Built ${branch} pack ${result.sequence_number} for ${subject}/${level} (${result.question_count}q)`);
  } catch (err) {
    console.error(`[autoGenerate] Failed to build ${branch} pack for ${subject}/${level}:`, err.message);
  }
}

// ── AutoGenerateDynamicPack ───────────────────────────────────────────────────
// Ensures minimum dynamic pack count for a scope.
// Pre-stocks all slots first, then assembles a dynamic pack.
async function autoGenerateDynamicPack({ curriculum, level, period, subject }) {
  const supabase = getSupabase();

  // Check how many active dynamic packs exist
  let packQ = supabase
    .from('trial_packs')
    .select('id', { count: 'exact', head: true })
    .eq('curriculum', curriculum)
    .eq('level', level)
    .eq('subject', subject)
    .eq('branch', 'dynamic')
    .eq('status', 'active');

  if (period) packQ = packQ.eq('period', period);
  else        packQ = packQ.is('period', null);

  const { count: packCount } = await packQ;
  if ((packCount || 0) >= PACK_MIN) return;

  const modules = await getActiveModules({ curriculum, level, period, subject });
  if (!modules.length) {
    console.warn(`[autoGenerate] No active modules found for dynamic pack: ${subject}/${level}`);
    return;
  }

  // Ensure every slot has the per-topic minimum (QUESTION_MIN[diff] per slot)
  for (const { module_number } of modules) {
    for (const diff of ['easy', 'medium', 'hard']) {
      await autoGenerateQuestions({ curriculum, level, period, subject, module_number, difficulty: diff });
    }
  }

  try {
    const result = await buildDynamicPack({
      curriculum,
      level,
      period,
      subject,
      module_numbers:      modules.map(m => m.module_number),
      questions_per_module: DYNAMIC_QPM,
    });
    console.log(`[autoGenerate] Built dynamic pack ${result.sequence_number} for ${subject}/${level} (${result.question_count}q, ${modules.length} modules)`);
  } catch (err) {
    console.error(`[autoGenerate] Failed to build dynamic pack for ${subject}/${level}:`, err.message);
  }
}

// ── checkAndAutoGenerate ──────────────────────────────────────────────────────
// Entry point — called after submit-pack-exam completes.
// Checks all three branches (easy/medium/hard + dynamic) for the scope.
// All checks fire as background setImmediate — never blocks the response.
function checkAndAutoGenerate({ curriculum, level, period, subject }) {
  const scope = { curriculum, level, period: period || null, subject };

  setImmediate(async () => {
    try {
      await Promise.all([
        autoGeneratePack({ ...scope, difficulty: 'easy'   }),
        autoGeneratePack({ ...scope, difficulty: 'medium' }),
        autoGeneratePack({ ...scope, difficulty: 'hard'   }),
        autoGenerateDynamicPack(scope),
      ]);
    } catch (err) {
      console.error('[autoGenerate] Background check failed:', err.message);
    }
  });
}

// ── Helpers ───────────────────────────────────────────────────────────────────
async function getActiveModules({ curriculum, level, period, subject }) {
  const supabase = getSupabase();

  let q = supabase
    .from('question_bank')
    .select('module_number, module_title')
    .eq('curriculum', curriculum)
    .eq('level', level)
    .eq('subject', subject)
    .eq('status', 'active')
    .not('module_number', 'is', null);

  if (period) q = q.eq('period', period);
  else        q = q.is('period', null);

  const { data } = await q;
  const seen = new Map();
  for (const row of data || []) {
    if (!seen.has(row.module_number)) seen.set(row.module_number, row.module_title);
  }
  return [...seen.entries()]
    .sort((a, b) => a[0] - b[0])
    .map(([module_number, module_title]) => ({ module_number, module_title }));
}

module.exports = { checkAndAutoGenerate, autoGenerateQuestions, autoGeneratePack, autoGenerateDynamicPack };
