-- ============================================================
-- Phase 3B: Question Bank + Generation Queue
-- Run in Supabase SQL editor after 001_curriculum_tables.sql
-- ============================================================

-- ── question_bank ─────────────────────────────────────────────────────────────
-- Individual questions generated by Claude, reused across sessions.
-- scope tiers: subtopic | general_topic | period

CREATE TABLE IF NOT EXISTS question_bank (
  id               BIGSERIAL PRIMARY KEY,
  question_id      TEXT UNIQUE NOT NULL,
  curriculum       TEXT NOT NULL DEFAULT 'tt_primary',
  level            TEXT NOT NULL,
  period           TEXT,
  subject          TEXT NOT NULL,
  scope            TEXT NOT NULL CHECK (scope IN ('subtopic', 'general_topic', 'period')),
  scope_ref        TEXT NOT NULL,       -- slugified: topic | module_title | period key
  topic            TEXT,               -- exact topic string (null for period scope)
  module_title     TEXT,               -- module name
  difficulty       TEXT NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')),
  question         TEXT NOT NULL,
  options          JSONB NOT NULL,     -- { "A": "...", "B": "...", "C": "...", "D": "..." }
  correct_answer   TEXT NOT NULL CHECK (correct_answer IN ('A', 'B', 'C', 'D')),
  explanation      TEXT,
  tip              TEXT,
  cognitive_level  TEXT,
  used_count       INTEGER NOT NULL DEFAULT 0,
  last_used_at     TIMESTAMPTZ,
  status           TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived', 'flagged')),
  source           TEXT NOT NULL DEFAULT 'generated',
  generated_at     TIMESTAMPTZ DEFAULT NOW()
);

-- Primary lookup: find questions for a given scope/difficulty slot
CREATE INDEX IF NOT EXISTS idx_qb_scope
  ON question_bank (curriculum, level, subject, scope, scope_ref, difficulty, status);

-- Pool freshness ordering: prefer unused, then least recently used
CREATE INDEX IF NOT EXISTS idx_qb_used
  ON question_bank (used_count ASC, last_used_at ASC NULLS FIRST)
  WHERE status = 'active';

-- ── question_bank_queue ───────────────────────────────────────────────────────
-- Generation jobs queued when a pool falls below the low watermark.
-- Railway cron (POST /api/v1/question-bank/process-queue) drains this.

CREATE TABLE IF NOT EXISTS question_bank_queue (
  id            BIGSERIAL PRIMARY KEY,
  curriculum    TEXT NOT NULL DEFAULT 'tt_primary',
  level         TEXT NOT NULL,
  period        TEXT,
  subject       TEXT NOT NULL,
  scope         TEXT NOT NULL,
  scope_ref     TEXT NOT NULL,
  difficulty    TEXT NOT NULL,
  target_count  INTEGER NOT NULL DEFAULT 30,
  status        TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending', 'processing', 'done', 'failed')),
  error_message TEXT,
  requested_at  TIMESTAMPTZ DEFAULT NOW(),
  completed_at  TIMESTAMPTZ
);

-- Fast scan for pending jobs (cron + replenish check)
CREATE INDEX IF NOT EXISTS idx_qbq_pending
  ON question_bank_queue (requested_at ASC)
  WHERE status = 'pending';
